name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  testing:
    name: "Testing"
    runs-on: "ubuntu-latest"

    env:
      PYTHONPATH:

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - uses: "actions-rs/toolchain@v1"
        with:
            toolchain: "1.57.0"

      - name: "[Python] Install dependencies"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade pip
          python -m pip install --requirement requirements.txt

      - name: "Advent of Code [Rust]"
        run: |
          cd advent_of_code
          ./run-tests rust

      - name: "Advent of Code [Python]"
        run: |
          export PYTHONPATH="$PWD"
          cd advent_of_code
          ./run-tests python
